#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    sortedA = sorted(a)
    res = 0

    numDict = {}
    for num in sortedA:
        if num not in numDict:
            numDict[num] = 1
        else:
            numDict[num] += 1
    
    numList = list(numDict.items()) 
    for idx in range(len(numList)):
        if idx != 0 and numList[idx][0] - numList[idx-1][0] <= 1:
            subArrayLength = numList[idx][1] + numList[idx-1][1]
            if res < subArrayLength:
                res = subArrayLength
                
        if res < numList[idx][1]:
            res = numList[idx][1]

    return res
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
